### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by nicefe** [ljunb/react-native-iShiWuPai#1]
[fsevents] Success: "/Users/zyd/lab/react-native-iShiWuPai/node_modules/react-native/node_modules/fbjs-scripts/node_modules/babel/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" is installed via remote
npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/zyd/.nvm/versions/node/v4.4.4/bin/node" "/Users/zyd/.nvm/versions/node/v4.4.4/bin/npm" "install"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@15.1.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native@0.26.3 wants react@15.0.2
npm ERR! peerinvalid Peer react-redux@4.4.5 wants react@^0.14.0 || ^15.0.0-0
npm ERR! peerinvalid Peer redux-devtools@3.3.1 wants react@^0.14.0 || ^15.0.0-rc.1

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zyd/lab/react-native-iShiWuPai/npm-debug.log

**Comment by ljunb** [comment]
@nicefe I have to update the project to 0.27, the corresponding react version is also updated to 15.1.0, which will solve your problem in the next commit
