### ISSUE TITLE
没有数据的时候 还显示加载更多 LoadFooter

### ISSUE THREAD

**Issue by BigLoafer** [ljunb/react-native-iShiWuPai#12]
_renderFooter = () => <LoadMoreFooter  flag={this.knowledgeListStore.flag}/>

   this.props.flag?<View style={styles.loadingContainer}>
                <ActivityIndicator />
                <Text style={styles.title}>正在加载更多的数据...</Text>
            </View>:<View style={styles.loadingContainer}>
                <Text style={styles.title}>已经没有数据啦...</Text>
            </View>
传入一个标志   显示不同的footer

**Comment by ljunb** [comment]
@BigLoafer 目前确实没有处理这个加载完所有数据时的Footer~有兴趣可以提PR的，欢迎任何修改意见😁

**Comment by ljunb** [comment]
根据实际返回的page和total_pages进行了判断[prompt title for LoadFooter](https://github.com/ljunb/react-native-iShiWuPai/pull/13)
