### ISSUE TITLE
app在安卓端运行显示空白页面，reload之后报如下错误

### ISSUE THREAD

**Issue by zouzheqiao** [ljunb/react-native-iShiWuPai#14]
![s70405-162628](https://cloud.githubusercontent.com/assets/22048736/24696781/4147fd54-1a1d-11e7-96d5-f2c0f8b038bb.jpg)

**Comment by kaoshen** [comment]
删除MainApplication中重写List下多余的RCTCameraPackage及相应的引用即可

**Comment by ljunb** [comment]
@kaoshen 是删掉然后重新引入RCTCameraPackage吗？这么神奇

**Comment by kaoshen** [comment]
@ljunb   代码clone下来，MainApplication的List参数有两个new RCTCameraPackage()，不知道为嘛有多余的。
