### ISSUE TITLE
安装后报了个错

### ISSUE THREAD

**Issue by debugksir** [ljunb/react-native-iShiWuPai#17]
Native module RCTCameraModule tried to override RCTCameraModule for module name RCTCameramodule.If this was your intention,set sanOverrideExistingModule=true

**Comment by clstudy** [comment]
你敲了 npm install && react-native link  的命令没？

**Comment by debugksir** [comment]
搞定了  不需要执行react-native link

**Comment by ljunb** [comment]
@debugksir @clstudy 今晚回去更新下：）

**Comment by handsome51jia** [comment]
安装上了，不能运行，第一个界面，红色界面，貌似，rn加载的时候，出现问题

**Comment by MicroKibaco** [comment]
遇到同样的问题贴上日志 undeitified is not a object(evaluating 'ViewPropTypes.style') DefaultTableBar.js:20

**Comment by ljunb** [comment]
最近比较忙，我本地也发现了这个问题，端午尽量找时间处理下 @handsome51jia @MicroKibaco

**Comment by ljunb** [comment]
@handsome51jia @MicroKibaco 我更新到了最新版，你们可以再更新试试。有空的话，计划把Redux给移除掉了，现在项目比较乱~

**Comment by ljunb** [comment]
已经完全移除Redux，接下来有空会再做进一步的代码优化，我就先关闭这个问题了~
