### ISSUE TITLE
NO dimension set for key window

### ISSUE THREAD

**Issue by giantss** [ljunb/react-native-iShiWuPai#18]
![simulator screen shot 2017 8 22 5 05 55](https://user-images.githubusercontent.com/13778798/29557754-a67ad15e-875c-11e7-8662-6b7edc0e40a9.png)
$ git clone https://github.com/ljunb/react-native-iShiWuPai.git
$ cd react-native-iShiWuPai 
$ npm install
$ react-native run-ios
运行模拟器报错

**Comment by ljunb** [comment]
@giantss 试试官方issues里面的处理方法 ["No dimensions set for key window" error after fresh 0.44.0 install](https://github.com/facebook/react-native/issues/13758)

**Comment by ljunb** [comment]
如果没什么问题，这个issue我就先关闭了
