### ISSUE TITLE
有时间来一个用户登录模块学习一下！

### ISSUE THREAD

**Issue by 85636682** [ljunb/react-native-iShiWuPai#2]
有时间来一个用户登录模块学习一下！谢谢

**Comment by ljunb** [comment]
@85636682 最近公司项目比较忙，都没什么时间来更新了

**Comment by junyangchen** [comment]
react native 微信登陆， 咋做？ 想做的童鞋请举手，一起探讨一下。

**Comment by ljunb** [comment]
@junyangchen 现在有相关组件，你可以搜react-native-wechat
