### ISSUE TITLE
FoodEncyclopedia.js 问题请教

### ISSUE THREAD

**Issue by yuyongmao** [ljunb/react-native-iShiWuPai#22]
react native的初学者，没有系统的学习过，所以想请教一下这个页面中的一些疑惑 叨扰了

想请教一下这两行代码里的 searchAction跟foodHandleAction
<HeaderView searchAction={this.searchAction}/>
<FoodHandleView handleAction={this.foodHandleAction}/>
在后面用的时候 一个是
 <TouchableOpacity
                    activeOpacity={0.75}
                    style={styles.headerSearchContainer}
                    onPress={searchAction}
                >
另一个是
<HandleItem title="饮食分析"
                        imageName={require('../../resource/ic_home_analyse.png')}
                        onPress={() => handleAction('饮食分析')}
            />

 一个是直接用了searchAction  另一个需要 () => handleAction('饮食分析')
这是为什么？谢谢啦

**Comment by yuyongmao** [comment]
或者是我需要看哪一方面的知识点 再次感谢

**Comment by ljunb** [comment]
`TouchableXXX` 组件的 `onPress` 接收一个点击事件，你列出来的 `searchAction` 其实对应到了类里面的 `this.searchAction` ，是保存了一个箭头函数的引用。

`onPress={() => handleAction('饮食分析')}` 这种写法，并不推荐，只不过这里是为了给父组件处理事件添加一个参数区分，所以传入了一个类 `type` 的参数 `饮食分析` ，这是一个带参数的函数，所以你也可以看到类里面 `this.foodHandleAction` 保存的，是一个带参数的箭头函数引用。

更推荐的写法，其实是 `HandleItem` 组件封装成类组件，在它内部的点击事件中，使用以下处理方式：
```
class HandleItem extends Component {
  handlePress = () => {
    const { onPress, title } = this.props; 
    onPress && onPress(title);
  };

  render() {
    return (
      <TouchableOpacity onPress={this.handlePress}>
        ...
      </TouchableOpacity>
    );
  }
}
```

这样的话，相应其他地方的使用方式：
```
const FoodHandleView = ({handleAction}) => {
  return (
    <View style={styles.foodHandleContainer}>
      <HandleItem
        title="饮食分析"
        imageName={require('../../resource/ic_home_analyse.png')}
        onPress={handleAction}
      />
      ...
    </View>
  )
};
```

相关的知识点，应该是 `JavaScript` 中函数是可以作为参数传递的，像我们经常写的某个函数传入了一个
 `callback` 这样。

**Comment by yuyongmao** [comment]
谢谢您的解答
