### ISSUE TITLE
看不见效果图也运行不起来

### ISSUE THREAD

**Issue by sfy666666** [ljunb/react-native-iShiWuPai#30]
萌新求助，无法运行项目
复现
用webstorm打开项目后再终端运行
1.yarn
2.react-native run-android
3.报错
Looks like you installed react-native globally, maybe you meant react-native-cli?
To fix the issue, run:
npm uninstall -g react-native
npm install -g react-native-cli
4.npm uninstall -g react-native
5.npm uninstall -g react-native
6.react-native run-android
7.报错
Looks like you installed react-native globally, maybe you meant react-native-cli?
To fix the issue, run:
npm uninstall -g react-native
npm install -g react-native-cli

然后就一直循环执行命令
npm uninstall -g react-native
npm install -g react-native-cli
反复报错
Looks like you installed react-native globally, maybe you meant react-native-cli?
To fix the issue, run:
npm uninstall -g react-native
npm install -g react-native-cli

救救孩子吧。。。

**Comment by ljunb** [comment]
项目版本较老，代码参考意义也一般，建议关注 https://github.com/attentiveness/reading 项目进行学习
