### ISSUE TITLE
请教关于redux的问题

### ISSUE THREAD

**Issue by lixuzong** [ljunb/react-native-iShiWuPai#4]
export default connect((state) => {
    const { Strolling } = state;
    return {
        Strolling
    }
})(StrollingContainer);
这里用{ Strolling }析构state，为什么可以取到？并没有看到state里面有与之名字相同的参数

**Comment by ljunb** [comment]
@lixuzong 你好，这里之所以能解析得到Strolling，是因为在rootReducer中将state拆分到了Strolling
