### ISSUE TITLE
运行不起来，如下图

### ISSUE THREAD

**Issue by Seven2Qin** [ljunb/react-native-iShiWuPai#5]
![image](https://cloud.githubusercontent.com/assets/14157210/20699104/7b098fee-b640-11e6-9728-a44514a7657a.png)

**Comment by Seven2Qin** [comment]
请作者帮忙看看

**Comment by Seven2Qin** [comment]
已经按照下面的提示操作过了，还是不行。请帮忙看看

**Comment by ljunb** [comment]
@Seven2Qin 试试这个链接的解决方法http://stackoverflow.com/questions/40730787/unable-to-resolve-module-react-lib-reactupdates，主分支很久没维护了，最近在做一次重构，有空更新上来

**Comment by ljunb** [comment]
@Seven2Qin RN版本已经更新到0.39.2，有兴趣可以重新下载，应该就可以正常运行了
