### ISSUE TITLE
请问这个是redux和mobx混写的吗？

### ISSUE THREAD

**Issue by RealAmissio** [ljunb/react-native-iShiWuPai#8]
怎么切换到mobx啊。。我看到好像都是基于redux写的

**Comment by ljunb** [comment]
@RealAmissio mobx目前是在alpha分支，readme有提到

**Comment by RealAmissio** [comment]
我下载了整个alpha分支啊。。。打开却还是用的redux
  "name": "iShiWuPai",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "mobx": "^2.7.0",
    "mobx-react": "^4.1.0",
    "react": "^15.4.0",
    "react-native": "^0.39.2",
    "react-native-easy-toast": "^1.0.5",
    "react-native-scrollable-tab-view": "^0.6.0",
    "react-redux": "^4.4.6",
    "redux": "^3.6.0",
    "redux-thunk": "^2.1.0"
  },
  "devDependencies": {
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-react-native-stage-0": "^1.0.1"
  }
}

**Comment by ljunb** [comment]
还没完全移除redux
