### ISSUE TITLE
application has not been registered

### ISSUE THREAD

**Issue by liuzhiyi1992** [ljunb/react-native-iShiWuPai#9]
![image](https://cloud.githubusercontent.com/assets/13046550/23288104/5efa3558-fa7c-11e6-8460-968d983582f3.png)

![image](https://cloud.githubusercontent.com/assets/13046550/23288107/68fe6c18-fa7c-11e6-8138-1a391e60d8d7.png)

**Comment by ljunb** [comment]
@liuzhiyi1992 看下你是不是开启了多个packager

**Comment by liuzhiyi1992** [comment]
@ljunb 请问开启了packager是指？

**Comment by liuzhiyi1992** [comment]
@ljunb run succeed, 关掉了其他packager
